FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive TZ=Europe/London

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    jq \
    git \
    tzdata \
    ca-certificates \
    expect \
    apt-transport-https \
    gnupg \
    lsb-release \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Docker
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
 && apt-get update \
 && apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Verify Docker installation
RUN docker --version && docker compose version

# Create a user for the runner
RUN useradd -m -g docker docker && echo "docker:docker" | chpasswd && adduser docker sudo \
    && echo "docker ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && usermod -aG docker docker

USER docker
WORKDIR /home/docker

# Download the GitHub runner
RUN curl -o actions-runner-linux-x64-2.325.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.325.0/actions-runner-linux-x64-2.325.0.tar.gz \
    && tar xzf ./actions-runner-linux-x64-2.325.0.tar.gz \
    && rm ./actions-runner-linux-x64-2.325.0.tar.gz

# Install GitHub runner dependencies
RUN sudo ./bin/installdependencies.sh

# Add the entrypoint script
COPY entrypoint.sh .
RUN sudo chmod +x entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
